[project]
name = "mypy-repro"
version = "0.0.0"
requires-python = ">= 3.10"

[build-system]
requires = ["setuptools>=0.61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }
